#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultra,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     combine,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     elevator,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    jack1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    jack2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    jack3,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    jack4,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DOUBLE_JOYSTICK true
#define SINGLE_JOYSTICK false
/*Brandon Wang, Lilia Heinold
Teleop 3565 (Name pending)
1.0 10/3 First Teleop Test (robot base)
1.1 11/7 Robot base with rolling goal servos
1.2 12/12 Redo motor/servo configurations for new base
*/
#include "JoystickDriver.c"
#include "Standard_Drive.c";
//#include "nxtIO.h";

void initializeRobot()
{
	motor[left] = 0;
	motor[right] = 0;
	nMotorEncoder[left] = 0;
}

float getAngle()
{
	getJoystickSettings(joystick);
	long y = joystick.joy1_y1;
	long x = joystick.joy1_x1;

	float angle = atan(y/x);
	return angle;

}

int adjustValue(int joystickValue)
{
	float value;
	int sign = 1;

	if(joystickValue < 0) sign *= -1;

	value = 100*pow(joystickValue,1.4)/pow(127,1.4);

	return (int) (value * sign);
}

float turnRadians(float rad)
{
	return ROBOT_RADIUS * rad * 2;
}

int getRightPower() //right motor power
{
	getJoystickSettings(joystick);

	long y2 = joystick.joy1_y2;
	long x2 = joystick.joy1_x2;
	long y = joystick.joy1_y1;
	long x = joystick.joy1_x1;
	float value;
	if(sqrt(x*x+y*y) > 10)
	{
		value =	(((y * y * y - x * x * x) * 100) >> 21);
	}
	else if (sqrt(x2*x2+y2*y2) > 10)
	{
		value = (((y2 * y2 * y2 - x2 * x2 * x2) * 100) >> 21) / 2;
	}
	else
	{
		value = 0;
	}

	return value;
}

int getLeftPower() //left motor power
{
	getJoystickSettings(joystick);

	long y2 = joystick.joy1_y2;
	long x2 = joystick.joy1_x2;
	long y = joystick.joy1_y1;
	long x = joystick.joy1_x1;
	float value;
	if(sqrt(x*x+y*y) > 10)
	{
		value =	(((y * y * y + x * x * x) * 100) >> 21);
	}
	else if (sqrt(x2*x2+y2*y2) > 10)
	{
		value = (((y2 * y2 * y2 + x2 * x2 * x2) * 100) >> 21) / 2;
	}
	else
	{
		value = 0;
	}
	return value;
}


task main()
{
	initializeRobot();
	bool joyStickMode = SINGLE_JOYSTICK;
	int angle = 0;

	while (true)
	{
		getJoystickSettings(joystick);

		long y2 = joystick.joy1_y2;
		long y = joystick.joy1_y1;

		if(abs(angle-getAngle()) > 5)
		{
			angle = getAngle();
			nMotorEncoder[left] = 0;
		}
		if(joyStickMode == DOUBLE_JOYSTICK)
		{
			//two joysticks
			if(sqrt(y2*y2+y*y) > 10)
			{
				motor[left] = y;
				motor[right] = y2;
			}
			else
			{
				motor[left] = 0;
				motor[right] = 0;
			}
		}
		if(abs(nMotorEncoder[motorD]) <= inchesToEncoder(turnRadians(getAngle())))
		{
			motor[motorD] = getLeftPower();
			motor[motorE] = getRightPower();
		}
		//one button at a time
		//First Controller Buttons
		if(joy1Btn(9) == 1 || joy1Btn(10) == 1)
		{ //Switch between dual and single joystick
			PlayTone(1000,5);
			joyStickMode = !joyStickMode;
			wait1Msec(1000);
		}

		if (joy2Btn(4) == 1 && joy2Btn(2) == 0)
		{
			servo[jack1] = ServoValue[jack1] + 5;
			servo[jack2] = ServoValue[jack2] - 5;

		}
		else if(joy2Btn(2) == 1 && joy2Btn(4) == 0)
		{
			servo[jack1] = ServoValue[jack1] - 5;
			servo[jack2] = ServoValue[jack2] + 5;
		}


		if (joy2Btn(1) == 1 && joy2Btn(3) == 0)
		{
			servo[jack3] = ServoValue[jack3] + 5;
			servo[jack4] = ServoValue[jack4] - 5;

		}
		else if(joy2Btn(3) == 1 && joy2Btn(1) == 0)
		{
			servo[jack3] = ServoValue[jack3] - 5;
			servo[jack4] = ServoValue[jack4] + 5;
		}
		//if (joy2Btn(7) == 1 && joy2Btn(8) == 0){
		//	motor[elevator] = 100;
		//}
		//else if (joy2Btn(8) == 0 && joy2Btn(7) == 0) {
		//	motor[elevator] = -100;
		//}


	}
}
