#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     combine,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     left2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     right1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     right2,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoR2,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoR1,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoL1,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoL2,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DOUBLE_JOYSTICK true
#define SINGLE_JOYSTICK false
/*Brandon Wang, Lilia Heinold, Will Engdahl
Teleop 3565 (Phantom Albert Lazarus)
1.0 10/3 First Teleop Test (robot base)
1.1 11/3 Robot base with elevator, and rolling goal servos
1.1 11/20 Added extra servos
1.3 Match #2 Day Making sure teleop is working
2.0: 1/8/15 New motor configs for rewired base
*/
#include "JoystickDriver.c"
#include "Standard_Drive.c";
#include "NXTio.c";

void initializeRobot()
{
	motor[left] = 0;
	motor[right] = 0;
	servo[lGrab1] = 0;
	servo[rGrab1] = 0;
	servo[lGrab2] = 0;
	servo[rGrab2] = 0;

	nMotorEncoder[elevator] = 0;
	nMotorEncoder[left] = 0;
	setMotors(left, right);

	bSystemLeaveServosEnabledOnProgramStop = true;
}

int adjustValue(int joystickValue)
{
	float value;
	int sign = 1;

	if(joystickValue < 0) sign *= -1;

	value = 100*pow(joystickValue,1.4)/pow(127,1.4);

	return (int) (value * sign);
}


task main()
{
	initializeRobot();


	waitForStart();
	bool joyStickMode = SINGLE_JOYSTICK;
	bool isCombineOn = false;
	while (true)
	{
		getJoystickSettings(joystick);

		//two joysticks

		long y2 = joystick.joy1_y2;
		long x2 = joystick.joy1_x2;
		long y = joystick.joy1_y1;
		long x = joystick.joy1_x1;

		long auxY2 = joystick.joy2_y2;

		if(joyStickMode == SINGLE_JOYSTICK)
		{
			//one Joystick
			if(sqrt(x*x+y*y) > 10)
			{
				motor[left] =			(((y * y * y + x * x * x) * 100) >> 21);
				motor[right] =		(((y * y * y - x * x * x) * 100) >> 21);
			}
			else if (sqrt(x2*x2+y2*y2) > 10)
			{
				motor[left] =			(((y2 * y2 * y2 + x2 * x2 * x2) * 100) >> 21) / 2;
				motor[right] =		(((y2 * y2 * y2 - x2 * x2 * x2) * 100) >> 21) / 2;
			}
			else
			{
				motor[left] = 0;
				motor[right] = 0;
			}
		}
		else
		{
			//two joysticks
			if(sqrt(y2*y2+y*y) > 10)
			{
				motor[left] = -y;
				motor[right] = -y2;
			}
			else
			{
				motor[left] = 0;
				motor[right] = 0;
			}
		}
		if(joy1Btn(9) == 1 || joy1Btn(10) == 1)
		{ //Switch between dual and single joystick
			PlayTone(1000,5);
			joyStickMode = !joyStickMode;
			wait1Msec(1000);
		}


		//Controls the elevator part. 4 goes up, 0 goes down
		//Controled by AUX
		if(joystick.joy2_TopHat == 0 && joystick.joy2_TopHat != 4)
		{
			motor[elevator] = 100;
		}
		else if(joystick.joy2_TopHat != 0 && joystick.joy2_TopHat == 4)
		{
			motor[elevator] = -100;
		}
		else
		{
			motor[elevator] = 0;
		}

		//controls the center
		if (joy1Btn(4) == 1 && joy1Btn(2) == 0)
		{
			servo[lGrab1] = ServoValue[lGrab1] + 5;
			servo[rGrab1] = ServoValue[rGrab1] - 5;
		}
		else if(joy1Btn(2) == 1 && joy1Btn(4) == 0)
		{
			servo[lGrab1] = ServoValue[lGrab1] - 5;
			servo[rGrab1] = ServoValue[rGrab1] + 5;
		}

		//controls the left aux grab
		//controled by DRIVER
		if (joy1Btn(7) == 1 && joy1Btn(5) == 0)
		{
			servo[lGrab2] = ServoValue[lGrab2] + 5;
		}
		else if(joy1Btn(5) == 1 && joy1Btn(7) == 0)
		{
			servo[lGrab2] = ServoValue[lGrab2] - 5;
		}
		//controls the right aux grab
		//controled by DRIVER
		if (joy1Btn(6) == 1 && joy1Btn(8) == 0)
		{
			servo[rGrab2] = ServoValue[rGrab2] + 5;
		}
		else if(joy1Btn(8) == 1 && joy1Btn(6) == 0)
		{
			servo[rGrab2] = ServoValue[rGrab2] - 5;
		}

		//Combine control mapped to right joy stick of auxiliary
		motor[combine] = auxY2;

		////control of the combine --> toggle (1 on, 3 off)
		////controled by AUX
		//if(joy2Btn(1) == 1&&joy2Btn(3) == 0)
		//{
		//	isCombineOn = true;	//**********************************CHECK THIS****************************//
		//}
		//else if(joy2Btn(3) == 1&&joy2Btn(1) == 0)
		//{
		//	isCombineOn = false;
		//}

		/*
		if(isCombineOn)
		{
			motor[combine] = 100;
		}
		else
		{
			motor[combine] = 0;
		}
*/
		if(joy2Btn(4) == 1 && joy2Btn(2) == 0)
		{
			servo[bucket] = ServoValue[bucket] + 2;
		}
		else if(joy2Btn(4) == 0 && joy2Btn(2) == 1)
		{
			servo[bucket] = ServoValue[bucket] - 2;
		}
	}
}
