#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    jack3,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    jack4,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    jack1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    jack2,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DOUBLE_JOYSTICK true
#define SINGLE_JOYSTICK false
/*Brandon Wang, Lilia Heinold, Will Engdahl
Teleop 3565 (Name pending)
1.0 10/3 First Teleop Test (robot base)
1.1 11/3 Robot base with elevator, and rolling goal servos
1.1 11/20 Added extra servos
--- 11/25 Added Documentation
*/
#include "JoystickDriver.c"
#include "Standard_Drive.c";
#include "nxtIO.h";

void initializeRobot()
{
	motor[left] = 0;
	motor[right] = 0;
	nMotorEncoder[elevator] = 0;
	nMotorEncoder[left] = 0;
}

void servoUp()
{
	//Put up servos (let go of tube)
	servo[jack1] = 225;
	servo[jack2] = 0;
	servo[jack3] = 255;
	servo[jack4] = 0;
}
void servoDown()
{
	//Put down servos (grab tube)
	servo[jack1] = 0;
	servo[jack2] = 225;
	servo[jack3] = 225;
	servo[jack4] = 0;
}

int adjustValue(int joystickValue) //Make joystick values more accurate
{
	float value;
	int sign = 1;

	if(joystickValue < 0) sign *= -1;

	value = 100*pow(joystickValue,1.4)/pow(127,1.4);

	return (int) (value * sign);
}


task main()
{
	initializeRobot();

	bool joyStickMode = SINGLE_JOYSTICK;
	while (true)
	{
		getJoystickSettings(joystick);

		//two joysticks

		long y2 = joystick.joy1_y2;
		long x2 = joystick.joy1_x2;
		long y = joystick.joy1_y1;
		long x = joystick.joy1_x1;

		if(joyStickMode == SINGLE_JOYSTICK)
		{
			//one Joystick
			if(sqrt(x*x+y*y) > 10)
			{
				motor[left] =			(((y * y * y + x * x * x) * 100) >> 21);
				motor[right] =		(((y * y * y - x * x * x) * 100) >> 21);
			}
			else if (sqrt(x2*x2+y2*y2) > 10)
			{
				motor[left] =			(((y2 * y2 * y2 + x2 * x2 * x2) * 100) >> 21) / 2;
				motor[right] =		(((y2 * y2 * y2 - x2 * x2 * x2) * 100) >> 21) / 2;
			}
			else {
				motor[left] = 0;
				motor[right] = 0;
			}
		}
		else {
			//two joysticks
			if(sqrt(y2*y2+y*y) > 10)
			{
				motor[left] = y;
				motor[right] = y2;
			}
			else
			{
				motor[left] = 0;
				motor[right] = 0;
			}
		}
		//one button at a time
		//First Controller Buttons
		if(joy1Btn(9) == 1 || joy1Btn(10) == 1)
		{ //Switch between dual and single joystick
			PlayTone(1000,5);
			joyStickMode = !joyStickMode;
			wait1Msec(1000);
		}

		if (joy2Btn(7) == 1 && joy2Btn(8) == 0) //Raise lift
		{
			motor[elevator] = 100;
		}
		else if(joy2Btn(8) == 1 && joy2Btn(7) == 0) //Lower lift
		{
			motor[elevator] = -100;
		}
		else //Stop lift
		{
			motor[elevator] = 0;
		}

		if (joy1Btn(4) == 1 && joy1Btn(2) == 0) //Grab tube/put down servos
		{
			servo[jack1] = ServoValue[jack1] + 5;
			servo[jack2] = ServoValue[jack2] - 5;
		}
		else if(joy1Btn(2) == 1 && joy1Btn(4) == 0) //Let go of tube/bring up servos
		{
			servo[jack1] = ServoValue[jack1] - 5;
			servo[jack2] = ServoValue[jack2] + 5;
		}

		if (joy1Btn(1) == 1 && joy1Btn(3) == 0) //Grab tube
		{
			servo[jack3] = ServoValue[jack3] + 5;
			servo[jack4] = ServoValue[jack4] - 5;
		}
		else if(joy1Btn(3) == 1 && joy1Btn(1) == 0) //Let go of tube
		{
			servo[jack3] = ServoValue[jack3] - 5;
			servo[jack4] = ServoValue[jack4] + 5;
		}


		if(joystick.joy2_TopHat == 0 && joystick.joy2_TopHat != 4) //Put down bucket
		{
			servo[bucket] = ServoValue[bucket] + 1;
		}
		else if(joystick.joy2_TopHat == 4 && joystick.joy2_TopHat != 0) //Pull up bucket
		{
			servo[bucket] = ServoValue[bucket] - 1;
		}


	}

	servoDown();
	servo[jack1] = 0;
	servo[jack2] = 225;
	servo[jack3] = 225;
	servo[jack4] = 0;
}
